### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by nmccann** [CocoaPods/cocoapods-repo-shard#3]
As discussed in [this blog post](http://blog.cocoapods.org/Master-Spec-Repo-Rate-Limiting-Post-Mortem/), sharding the master repo introduces backwards-incompatible changes. In our organization we share CI servers and use Bundler along with a Gemfile to specify versions for dependencies, but different versions share the same `~/.cocoapods` directory. 

This hasn't been a problem in the past, but with the introduction of sharding it looks like we will no longer be able to share the same `~/.cocoapods` with projects that haven't been updated to Cocoapods 1.0.0.

Looking through the CLI I haven't found a mechanism for specifying a custom `~/.cocoapods` directory, which would allow us to have a legacy directory and one for 1.0.0. Is such a thing possible?

That being said, separating directories seems like only part of the problem because old versions of Cocoapods will try to update their specs repo but will get the new sharded version which they can't parse. Perhaps there is a way to "freeze" these legacy projects so they don't update their copy of the specs repo. Or would you recommend we fork the repo in it's current state and update these legacy projects to use that fork in favour of the sharded repo?

I'm sorry if this isn't the right location for such questions, I could move it to the Cocoapods repo if that would be preferable.

**Comment by segiddins** [comment]
We're going to have to drop support for pre-1.0 versions using the master repo in a few months. You can [set the `CP_REPOS_DIR` env var](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/config.rb#L127-L129) to control what repo directory is used, as well as manually check out the (I believe it will be) `0.32.1` tag in the master specs repo manually (or use `--no-repo-update`).

post 1.0, such upgrades will automatically be handled by CocoaPods, but for now the official advice is upgrade to 1.0 -- we won't be support older versions anyways, and the master specs repo _will_ have to be shredded in the coming months.

**Comment by nmccann** [comment]
Thank you for the quick response @segiddins, much appreciated
